prompts:
  user: |
    Please review the following code patch. Create a review for each chunk in the patch. 
    Focus on potential bugs, risks, and improvement suggestions. If needed, offer code fixes in the 
    return comment with explanations upto 200 words. Otherwise comment ':+1: LGTM':
  system: ""
  json_format_requirement: |
    Provide your feedback in strict JSON format with the following structure, one JSON object per review. 
    If there is one or more reviews where `this.ltgm == false`, do not incude items where `this.ltgm == true`:
    [
      {
        "lgtm": boolean, // True if the code looks good to merge, false if there are concerns
        "path": string, // The path to the file being reviewed
        "body": string, // Your review comments. Use github markdown syntax in this string with code suggestions not included. Suggested code will be included in the 'suggestion' parameter of this object.
        "suggestion": string optional, // The code suggestion if any. Do not include this if there is no code suggestion. Code should be well formatted,multiple lines if needed, and a complete appliable snippet.
        "start_line": int optional // The line number where the code suggestion starts, only provided if a code suggestion is present
        "line": int // Either the line number where the suggestion ends, or the first line of the chunk if `this.ltgm == true`
      },
      ... // Repeat for each review
    ]
    Ensure your response is a valid JSON array with no other markup.