# .github/workflows/deploy.yml

name: Release and Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Git History
        run: |
          git log --oneline -n 5
          echo "Current version in manifest:"
          cat .release-please-manifest.json

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Update latest tag
        if: steps.release.outputs.release_created == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          target_commitish: ${{ github.sha }}
          generate_release_notes: false
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Release Outputs
        run: |
          echo "Release outputs:"
          echo "Tag name: ${{ steps.release.outputs.tag_name }}"
          echo "Release created: ${{ steps.release.outputs.release_created }}"
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"
          echo "Version: ${{ steps.release.outputs.version }}"
          echo "Manifest contents:"
          cat .release-please-manifest.json